# Stage 1: Build the JAR
FROM gradle:jdk11 as gradle
COPY --chown=gradle . /home/app
WORKDIR /home/app
RUN gradle assemble --no-daemon

# Stage 2: Build the native image
FROM ghcr.io/graalvm/graalvm-ce:latest as graalvm
# For SDKMAN to work we need unzip & zip
#RUN yum install -y unzip zip
RUN \
    # Install GraalVM Native Image
    gu install native-image;
COPY --from=gradle /home/app/build/libs/*-all.jar /home/app/server.jar
WORKDIR /home/app
RUN native-image --no-server -cp server.jar

# Stage 3: Prepare Server
FROM frolvlad/alpine-glibc:latest
EXPOSE 8080
COPY --from=graalvm /home/app/greetings-cloud-run .
ENTRYPOINT ["./greetings-cloud-run"]